name: Update Labels for All Issues Based on Status

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  update_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Listar todas as issues do repositório
      - name: Get all issues
        run: |
          ISSUES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&per_page=100" | jq -r '.[].number')
          echo "::set-output name=issues::$ISSUES"
        id: issue_output

      # Para cada issue, obter o status e aplicar a label correspondente
      - name: Update labels for each issue
        run: |
          for ISSUE in ${{ steps.issue_output.outputs.issues }}
          do
            # Obter status da issue
            STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE | jq -r '.labels[].name')
            
            echo "Processando issue #$ISSUE com status $STATUS"

            # Remover labels antigas e adicionar novas com base no status
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE/labels/Todo,In%20Progress,Done

            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"labels":["'$STATUS'"]}' \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE/labels
          done
