name: Update Issue Labels Based on Status

on:
  project_card:
    types: [moved]

jobs:
  update_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get project card status
        run: |
          STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/projects/columns/${{ github.event.project_card.column_id }} | jq -r '.name')

          echo "Status atual: $STATUS"
          
          # Define as labels de status válidas
          VALID_LABELS=("Todo" "In Progress" "Done")

      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'Todo,In Progress,Done' # Remove todas as labels de status anteriores

      - name: Actions Ecosystem Add Labels
        if: ${{ contains(VALID_LABELS, env.STATUS) }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.STATUS }}  # Adiciona a label correspondente ao status atual
