name: Update Issue Labels Based on Status

on:
  project_card:
    types: [moved]

jobs:
  update_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Remover labels anteriores (Todo, In Progress, Done)
      - name: Remove previous labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Todo
            In Progress
            Done

      # Adicionar nova label com base no status
      - name: Add new label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'In Progress'  # Aqui você pode alterar para o status que desejar

      # Obter a última tag do repositório (opcional)
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
