name: Update Labels Based on Project Card Movement

on:
  project_card:
    types: [moved]  # Aciona o workflow quando um card é movido

jobs:
  update_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Obter o número da issue a partir da URL do cartão de projeto
      - name: Get issue number from project card
        id: get_issue_number
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.project_card.content_url }}" | grep -oE '[0-9]+$')
          echo "Número da Issue: $ISSUE_NUMBER"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV

      # Obter o status da coluna para onde a issue foi movida
      - name: Get project card status
        id: get_status
        run: |
          STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/projects/columns/${{ github.event.project_card.column_id }}" | \
            jq -r '.name')
          echo "Status atual: $STATUS"
          echo "status=$STATUS" >> $GITHUB_ENV

      # Remover labels de status anteriores
      - name: Remove previous status labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Todo
            In Progress
            Done
          number: ${{ env.issue_number }}

      # Adicionar nova label correspondente ao status atual
      - name: Add new label based on current status
        if: env.status != ''
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.status }}
          number: ${{ env.issue_number }}
