name: Update Status Labels

on:
 workflow_dispatch:  # Permite execução manual
  project_card:
    types: [moved]

jobs:
  update-label:
    runs-on: ubuntu-latest

    steps:
    - name: Apply label based on project card movement
      uses: actions/github-script@v3
      with:
        script: |
          // Definir as labels de status: 'Todo', 'In Progress', 'Done'
          const statusLabels = ['Todo', 'In Progress', 'Done'];
          
          // Obter o nome da coluna do Kanban para onde o card foi movido
          const columnName = context.payload.project_card.column_name;

          // Verificar se o nome da coluna corresponde a uma das labels de status
          const newStatusLabel = statusLabels.find(label => label === columnName);

          if (newStatusLabel) {
            // Obter o número da issue a partir da URL do cartão do projeto
            const issue_number = context.payload.project_card.content_url.split('/').pop();

            // Adicionar a nova label de status à issue
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: [newStatusLabel]
            });
          }
