name: Update Labels Based on Issue Status

on:
  issues:
    types: [opened, edited, closed]  # Aciona o workflow para alterações na issue

jobs:
  update_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Obter o status da issue (considerando que o status está definido em uma label)
      - name: Get current status label
        id: get_status
        run: |
          CURRENT_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" | \
            jq -r '.labels[] | select(.name | test("Todo|In Progress|Done")) | .name')
          echo "Current status: $CURRENT_STATUS"
          echo "::set-output name=status::$CURRENT_STATUS"

      # Remover labels de status anteriores
      - name: Remove previous status labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Todo
            In Progress
            Done
          number: ${{ github.event.issue.number }}

      # Adicionar nova label correspondente ao status atual
      - name: Add new label based on current status
        if: steps.get_status.outputs.status != ''
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.get_status.outputs.status }}
          number: ${{ github.event.issue.number }}
